Public reservation API
vjekob/al-objid pull request #55
Opened 2023-01-29 18:06 UTC by anzwdev

A new public api class that can be used by other VS Code extensions to get IDs suggestions and to reserve them. There are 2 methods in the api
- `suggestIds` to get list of suggested IDs (1 for each ID range) without reserving them
- `reserverId` to reserve a single ID

``` javascript
let idNinjaExtension = vscode.extensions.getExtension("vjeko.vjeko-al-objid");
if ((idNinjaExtension) && (idNinjaExtension.isActive)) {
    let api = idNinjaExtension.exports;
    let ids = await api.suggestIds(uri, type);
}
```

2023-03-22 08:59 UTC, fvet commented
@vjekob  Any chance in merging this PR into the AL Object Ninja master?

It would help us in adopting AZ AL Dev Tools combined with the power of AL Object ID Ninja ;)
https://github.com/anzwdev/al-code-outline/issues/276

2023-03-24 16:05 UTC, vjekob commented
> @vjekob Any chance in merging this PR into the AL Object ID Ninja `master`?
> 
> It would help us in adopting AZ AL Dev Tools combined with the power of AL Object ID Ninja ;) [anzwdev/al-code-outline#276](https://github.com/anzwdev/al-code-outline/issues/276)

Yes, I am going to merge this PR and release a new version shortly.

2023-03-25 22:16 UTC, vjekob commented on vscode-extension/package.json
> -    "version": "2.9.2",
Please don't do this in future submissions. I'd like to control versioning of the extension myself. These kinds of changes are making my job more difficult.

2023-03-25 22:21 UTC, vjekob requested changes
Sorry, can you please exclude package-lock.json and package.json from this PR?

2023-03-26 08:19 UTC, merged

2023-03-26 08:20 UTC, vjekob commented
I've decided to fix this myself as I want this feature to be a part of Ninja's next release.

Thanks for your contribution! 😊

2023-03-26 11:43 UTC, anzwdev commented
That's great. Thank you :)